// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa9JCyoD0QiOix9esVy-0UABR6gAn7RmQ',
    appId: '1:159322989549:web:f7ac74dc4ab11bd707fde4',
    messagingSenderId: '159322989549',
    projectId: 'atividade-login1',
    authDomain: 'atividade-login1.firebaseapp.com',
    databaseURL: 'https://atividade-login1-default-rtdb.firebaseio.com',
    storageBucket: 'atividade-login1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8y-D02bAirUoKn4m-yo6gPXm6ODviZY',
    appId: '1:159322989549:android:55ab0802c3d73d9407fde4',
    messagingSenderId: '159322989549',
    projectId: 'atividade-login1',
    databaseURL: 'https://atividade-login1-default-rtdb.firebaseio.com',
    storageBucket: 'atividade-login1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsZXYQHNBp1FA93Q3vKSWdINU2DiRP8k',
    appId: '1:159322989549:ios:799362a8144ab55107fde4',
    messagingSenderId: '159322989549',
    projectId: 'atividade-login1',
    databaseURL: 'https://atividade-login1-default-rtdb.firebaseio.com',
    storageBucket: 'atividade-login1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADsZXYQHNBp1FA93Q3vKSWdINU2DiRP8k',
    appId: '1:159322989549:ios:8f76c2641e89237007fde4',
    messagingSenderId: '159322989549',
    projectId: 'atividade-login1',
    databaseURL: 'https://atividade-login1-default-rtdb.firebaseio.com',
    storageBucket: 'atividade-login1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
